blank_issues_enabled: false
contact_links:
  - name: TanStack Query documentation
    url: https://tanstack.com/query/latest/docs/framework/react/overview
    about: For questions about TanStack Query itself.
  - name: Astro documentation
    url: https://docs.astro.build
    about: For questions about Astro itself.
